### ISSUE TITLE
Typing in search bar triggers seeking

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#1]
Reproduce steps:
1. Open any YouTube shorts
2. Type J or L in the search bar

**Comment by dekotale** [comment]
This is fixed in my pull request: #10 @ynshung

**Comment by HealingArcYT** [comment]
I think it fits here. Same thing happens when answering to a cmment on a short, it just goes through frame by frame with . and , it changes the speed with u, i, o. if on default settings i go to the next/previous short with w and s. also it mutes on m
