### ISSUE TITLE
v3 compatibility to Firefox

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#101]
Currently, the only way to make the v3 version work on Firefox is to build the extension with `npm run build`, change the `"service_worker": "service-worker-loader.js"` to `"scripts": ["service-worker-loader.js"]` and load the extension from there. So working iteratively will be a hassle.

Though there are PR to the extension builder that adds compatibility such as https://github.com/crxjs/chrome-extension-tools/pull/644, HMR still is not implemented.

Some issues I run across:
- Need to open the extension for the first time for it to work
- Inconsistent text size compared to Chrome

**Comment by adsuth** [comment]
> Need to open the extension for the first time for it to work

Figured out you can right click the extension to always allow it to run without having to open it.
Might be a way to programmatically ask for permission, though I'm not sure. Wouldnt think so though.

<img width="358" alt="image" src="https://github.com/ynshung/better-yt-shorts/assets/74009107/697802ca-2ffc-4495-bc41-15b40fdd3fbc">

**Comment by ynshung** [comment]
> > Need to open the extension for the first time for it to work
> 
> Figured out you can right click the extension to always allow it to run without having to open it. Might be a way to programmatically ask for permission, though I'm not sure. Wouldnt think so though.
> 
> <img alt="image" width="358" src="https://user-images.githubusercontent.com/74009107/268129923-697802ca-2ffc-4495-bc41-15b40fdd3fbc.png">

I searched around online and see some mention that the `host_permissions` need to be added into the manifest. But from my testing it doesn't seems to work. Probably a bug of how v3 interact with Firefox?

**Comment by ynshung** [comment]
Fixed on 52f6e48912804eb99733ace6435d1bf6a3ab38aa: just use manifest v2. Dealing with manifest v3 is a hassle in Firefox
