### ISSUE TITLE
Writing comment triggering the key shortcuts

### ISSUE THREAD

**Issue by jovyllebermudez** [ynshung/better-yt-shorts#103]
Thank you for creating such a useful extension.
What I noticed when writing comments it triggered the hotkeys.

**Comment by adsuth** [comment]
Hi, can I get more info
- Which version of the extension are you using (I know this issue was in 2.8.1, but I thought I addressed it)
- What sort of comment (reply, standard comment)

**Comment by jovyllebermudez** [comment]
Oh, I removed my extension and installed the one said "NEW LINK" and its fixed.
My apologies.
