### ISSUE TITLE
Move overlayed text off from short

### ISSUE THREAD

**Issue by TychoWerner** [ynshung/better-yt-shorts#110]
Hi, I would like to see a function to move all text of the short. See example issue here:
<img width="449" alt="Scherm­afbeelding 2023-09-18 om 12 00 39" src="https://github.com/ynshung/better-yt-shorts/assets/34608981/f53bac30-4b53-4cc0-ad4f-31e2281ba8c1">

Some suggested layout would be like this:
<img width="621" alt="Scherm­afbeelding 2023-09-18 om 12 03 30" src="https://github.com/ynshung/better-yt-shorts/assets/34608981/4017c7fa-4334-41d6-baf7-18f54829e918">

**Comment by adsuth** [comment]
adding an additional panel for text content may be a challenge, but I think we could fairly easily add an option to toggle the text at the bottom of the screen as a step in that direction like so

<img width="500" alt="image" src="https://github.com/ynshung/better-yt-shorts/assets/74009107/934326d8-14ff-4295-b650-03612b25adef">

**Comment by TychoWerner** [comment]
Yep just hiding the text all along is also fine :)
