### ISSUE TITLE
Can't see timestamp in light theme

### ISSUE THREAD

**Issue by jarsang002** [ynshung/better-yt-shorts#13]
I usually use youtube in light theme but timestamp is invisible. I have to drag cursor over to make it visible.
Can you fix it?

![mspaint_Cq9s7p34yK](https://user-images.githubusercontent.com/57130931/215358977-33e4487d-d3fc-47a2-9a67-f001e9761b55.png)

**Comment by ynshung** [comment]
Closed from #15
