### ISSUE TITLE
skipping any short bellow 500 likes even with lower threshold

### ISSUE THREAD

**Issue by zeinterrupter** [ynshung/better-yt-shorts#133]
I tried to set the like threshold to 50 likes so it skips anything below that but instead it auto skips shorts with 100+, i believe until 500 like the default setting

**Comment by adsuth** [comment]
I'm noticing that the option doesnt work if the like count has no modifier...

I think youtube has changed the HTML since I added the option as well. Will fix it asap

**Comment by zeinterrupter** [comment]
alright thank you!
