### ISSUE TITLE
Scroll on volume bar to adjust volume

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#137]
Since we have scrolling on timestamp and speed to adjust them respectively, the user should be able to adjust the volume bar with scrolling as well

**Comment by SamiSul** [comment]
@ynshung I'd love to implement this. How would this work? Can you assign me? Thanks <3

**Comment by ynshung** [comment]
Sure thing! Thanks for the initiative

**Comment by adsuth** [comment]
> I'd love to implement this. How would this work? Can you assign me? Thanks <3

Are you familiar with contributing to open source? If you need a hand lmk and I'll try to point you in the right direction

**Comment by SamiSul** [comment]
@adsuth Hi, I've never contributed before, I know I have to fork the repo, make changed then create a PR but I'd be great if you have more tip :)

**Comment by SamiSul** [comment]
[here is the PR](https://github.com/ynshung/better-yt-shorts/pull/139)

**Comment by ynshung** [comment]
Closes from #139
