### ISSUE TITLE
Volume slider and keys not working 

### ISSUE THREAD

**Issue by yasinULLAH** [ynshung/better-yt-shorts#14]
after playing 8 to 20 shorts the volume slider disappear and shortcut keys (+ and -) stops working.

**Comment by MichaelDavidGK** [comment]
up
same thing on both firefox and chrome, sometimes happen even on fresh install
had to change at least one of keybinds for it to start working again, which isn't possible on firefox

**Comment by ynshung** [comment]
Hello @yasinULLAH and @MichaelDavidGK, would you test again on the latest version to see if this still happens?

**Comment by MichaelDavidGK** [comment]
Works now,
Thank you ;)

**Comment by yasinULLAH** [comment]
Thanks alot it's working now but there is another problem now with normal YouTube video when I enter fullscreen or when I exit the fullscreen the youtube player loses focus means i can't raise or lower volume by up and down arrows

**Comment by monsieurvor** [comment]
I'll have a look

**Comment by monsieurvor** [comment]
I checked in Chrome and Firefox, and the keybinds for up and down work for normal youtube. @yasinULLAH what browser are you using? Did you update the extension?

**Comment by yasinULLAH** [comment]
@monsieurvor I am using google chrome and did checked it and updated chrome and extension but still the problem persist only when I goto full screen in youtube by pressing F key on keyboard then the player loses focus and the up and down keys stops working also when exit out of full screen by pressing F key the same thing unless I click again in the middle of the player again to re-focus it.
