### ISSUE TITLE
Show views count not working on Firefox

### ISSUE THREAD

**Issue by tiagohconte** [ynshung/better-yt-shorts#153]
**Describe the bug**
Views count feature don't work on Firefox.

**Expected behavior**
The views count is expected to appear above the Shorts title.

**Screenshots**
|Chromium|Firefox|
|-|-|
|![image](https://github.com/ynshung/better-yt-shorts/assets/54898879/db3dfc60-0486-461b-ad25-7601bb65dd82)| ![image](https://github.com/ynshung/better-yt-shorts/assets/54898879/904810f0-ffe6-4b19-8fc4-c83fb5b2adf0)|

**Desktop:**
 - OS: any
 - Browser Firefox
 - Version 3.1.0

**Additional context**
For some reason, the "Firefox version" of YouTube doesn't have the `aria-label` item in the element used to get the views at this [line](https://github.com/ynshung/better-yt-shorts/blob/43312aeec6840665e10190b62f1f6eb998d9f9bf/src/lib/getters.ts#L130). It can be fixed by getting the `textContent` from the div.

**Comment by samisul** [comment]
on it

**Comment by samisul** [comment]
@ynshung can this be closed?
