### ISSUE TITLE
Timestamps in short URLs don't work anymore

### ISSUE THREAD

**Issue by BreadBreadington** [ynshung/better-yt-shorts#155]
I believe this was a Youtube change but I could be wrong
Previously you could add the "t=[number]" option to a short URL and it would work the same as a normal video.

An alternative change could be making the "Copy video URL at current time" context menu options link to the full-sized video (youtube.com/watch?v= instead of youtube.com/shorts)

**Comment by ynshung** [comment]
Seems like a YouTube change, the option to add current time in the video is disabled entirely. Maybe the extension could check if the "t=" attribute exists and seek automatically. But one issue is that the attribute automatically get removed so we need to test if it is even detectable, if at all.

**Comment by adsuth** [comment]
> Seems like a YouTube change, the option to add current time in the video is disabled entirely. Maybe the extension could check if the "t=" attribute exists and seek automatically. But one issue is that the attribute automatically get removed by YouTube when the video loads so we need to test if it is even detectable, if at all.

i dont think it is. Tried it with the dev console. By the time the page loads, the urls already changed. 

The suggestion to link to the full view at the specific time on the other hand might work.

Basically we could just emulate the share modal on full videos
<img width="509" alt="image" src="https://github.com/ynshung/better-yt-shorts/assets/74009107/c2ba0fb2-81e5-485e-b64b-df732ebdf93a">

adding a new section under the one thats there maybe
<img width="562" alt="image" src="https://github.com/ynshung/better-yt-shorts/assets/74009107/864f1a74-5b72-4361-8e13-8296a4915868">

Seems like a lot of work for not a lot of gain though. Shorts are, short, and seeking to the correct time is fairly easy with the progressbar implementation (or just seeking forward)

**Comment by ynshung** [comment]
Closing this as not planned for now, anyone who is interested in this feature or work on it can comment below
