### ISSUE TITLE
Toggling of the view counter and upload date

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#161]
As #140 and #154 have added the views number and upload date above the title, there should be an option for the user to individually disable each of them on the `Toggle Features` tab, i.e. "Enable View Counter" and "Enable Upload Date"

Note that care should be taken to make sure the options is added in the `declarations.ts`, localization etc.

**Comment by dhanasekaranc** [comment]
@ynshung can you assign this issue to me? I would like to work on this.

**Comment by ynshung** [comment]
Go ahead @dhanasekaranc! Feel free to leave any questions or comments here

**Comment by dhanasekaranc** [comment]
@ynshung can I know where can we find the `Toggle features tab` referred above?

**Comment by ynshung** [comment]
> @ynshung can I know which section you refer to as `Toggle features tab`?

This toggle features tab:
![image](https://github.com/ynshung/better-yt-shorts/assets/61302840/99d31324-4efc-4eb4-ac36-7aa32e82d226)
