### ISSUE TITLE
All features are enabled but View Counter doesn't work

### ISSUE THREAD

**Issue by GitAcc53** [ynshung/better-yt-shorts#168]
I can't see the number of views anymore. I tried in both Chrome and Brave.

edit : upload date is also not shown. 3 days ago upload date was shown and view counter was not shown, now they are both not shown.

I also have a feature request but not that important. I think "Playback Rate" should be just a text like the "Timer". Currently it looks ugly

**Comment by ynshung** [comment]
Unfortunately the number of views that we got from the YouTube's code has been removed, there is currently no workaround for this yet

**Comment by GitAcc53** [comment]
> Unfortunately the number of views that we got from the YouTube's code has been removed, there is currently no workaround for this yet

Will you guys add it back when it is possible to add it again?

**Comment by ynshung** [comment]
> > Unfortunately the number of views that we got from the YouTube's code has been removed, there is currently no workaround for this yet
> 
> Will you guys add it back when it is possible to add it again?

Yup definitely, going to open another issue for this
