### ISSUE TITLE
Ability to show shorts' views (again)

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#173]
As of 2023/10/31, internal changes from YouTube removed the number of views are from the description section. Hopefully an alternative can be found to add back this functionality into the extension

Related to #169 and its mentioned PR

**Comment by ynshung** [comment]
Searching around the source code of the shorts, I found this following section that displays the view count:
![image](https://github.com/ynshung/better-yt-shorts/assets/61302840/37f70e52-c631-4990-9b2e-b4b456f38348)

But when you go to the next shorts it won't update in the source since the data is fetched directly:

![image](https://github.com/ynshung/better-yt-shorts/assets/61302840/5ad3d3e9-8f42-4fa8-b581-a23a5cdada73)

Using YouTube's v3 API seems to be not feasible seeing it will probably go over the quota easily

**Comment by samisul** [comment]
@ynshung can you assign me this please? will look into it and try to find a way

**Comment by ynshung** [comment]
Hello @samisul any updates on this?

**Comment by samisul** [comment]
> Hello @samisul any updates on this?

Hey, haven't been able to work on this a lot but from what I've tried so far I have the following notes:

- The view count doesn't exist anywhere in any element so no hope there
- as far as I can tell the only way to get the views is to intercept the http call via [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch)

I'm gonna try to work on this tomorrow but feel free to give it a try

**Comment by adsuth** [comment]
Could potentially look into integrating the youtube data api. Itd open a lot of doors in terms of potential features - including getting metrics for shorts

Not sure of the feasibility though, and it'd need an api key. Also im only assuming it works with shorts

**Comment by samisul** [comment]
@adsuth hmmm very interesting idea, will look into that too
