### ISSUE TITLE
Volume Slider Injection Fails, Causes Buttons to be Added Multiple Times

### ISSUE THREAD

**Issue by derLesh** [ynshung/better-yt-shorts#177]
**Describe the bug**
When opening a Short Video the Autoplay and Playback Speed button gets added multiple times and throwing an error in the console.

**To Reproduce**

1. Open any Shorts on Youtube

**Expected behavior**
Only once the button will be created

**Screenshots**
![image](https://github.com/ynshung/better-yt-shorts/assets/11671272/934a7fd7-a271-46eb-8540-ab4d01d627b3)
![image](https://github.com/ynshung/better-yt-shorts/assets/11671272/12414f4e-7423-4175-8d0d-7831cdbb1c00)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version 119.0.6045.160

**Additional context**
Tested without any other extension enabled.

The error in the console is thrown by this line here: https://github.com/ynshung/better-yt-shorts/blob/671a2eef3e9c8e568a842a55eb985eee7f16aa56/src/lib/VolumeSlider.ts#L70C3-L70C39

**Comment by Insane-Owl** [comment]
same issue here
