### ISSUE TITLE
Volume bar has disappeared

### ISSUE THREAD

**Issue by Qu1tus** [ynshung/better-yt-shorts#179]
**Describe the bug**
I can't modify the volume on shorts anymore. The volume bar has disappeared.
**To Reproduce**
No steps in particular, no change on chrome whatsoever

**Expected behavior**
The volume bar should be in the top corner of the short?

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser : Chrome
- Version 119.0.6045.160

**Additional context**

**Comment by fetusfajita** [comment]
same issue on firefox, also multiple auto play buttons appear instead of the volume adjuster

**Comment by adsuth** [comment]
Duplicate issue of #177 (this is caused by the same problem)
