### ISSUE TITLE
auto play and speed control is duplicate

### ISSUE THREAD

**Issue by Abdullah-albagshi** [ynshung/better-yt-shorts#180]
**Describe the bug**
as the title said the controls are duplicates and the volume control is not showing 

**To Reproduce**
open any short video

**Expected behavior**
controls will duplicate

**Screenshots**
<img width="591" alt="Screenshot 2023-11-22 at 7 44 01 PM" src="https://github.com/ynshung/better-yt-shorts/assets/52722148/5f85120b-a07d-4b37-b83e-3fb11f34a28d">

**Desktop (please complete the following information):**

- OS: mac and windows 
- Browser: Chrome

**Comment by ynshung** [comment]
Should be fixed at v3.2.3. If your browser does not automatically update the extension, you can try relaunching your browser or reinstalling the extension.
