### ISSUE TITLE
Possible memory leak and/or lagging bug. 

### ISSUE THREAD

**Issue by DevRustic** [ynshung/better-yt-shorts#184]
**Describe the bug**
Multiple autoplay checkers pop up, and eventually browser starts to go WAY up in memory, (opera GX goes from about 200-400 MB's of memory to over 1.5GB within 3 minutes.

Insane lag to the point where youtube doesnt work. 

**To Reproduce**

1. Using version v3.2.3
2. Then it just happens, sometimes it doesnt, nothing changes between the times that it happens and doesnt
3. Happens on all browsers ive used (chrome, opera gx)

**Expected behavior**

Not lag, no multiple autoplay bars, etc

**Screenshots**

![image](https://github.com/ynshung/better-yt-shorts/assets/18624826/e0fa2357-7b5c-40e5-9e86-4f2ef2bb4b6e)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome and Opera GX
- Version v3.2.3

**Comment by fetusfajita** [comment]
same issue here, using firefox on MacOs High Sierra

**Comment by ynshung** [comment]
Fixed in v3.2.4, please check if your browser had automatically update the extension to the latest version
