### ISSUE TITLE
Has no effect on KIwi Browser (chromium fork for android) 

### ISSUE THREAD

**Issue by Ryder17z** [ynshung/better-yt-shorts#186]
**Describe the bug**
Not functional at all on Kiwi (chromium fork) 

**To Reproduce**

1. Install Kiwi Browser, add this extension. 
2. Maybe restart browser (not sure if required) 
3. Open a shorts video and watch the extension have no effect. 

**Expected behavior**
An error message or anything useful, it's as if the extension is not installed at all. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Android 10
- Browser: KIwi Browser 
- Version 116.0.5845.57 

**Additional context**
N/A

**Comment by ynshung** [comment]
Sorry but we're currently not planning on supporting this extension on Android (yet), thank you for your interest!

**Comment by Ryder17z** [comment]
it was worth trying it out though.
