### ISSUE TITLE
Previous Issue that was solved I am still experiencing. Scroll bar does not load only when signed in on my account.  

### ISSUE THREAD

**Issue by kyfry327** [ynshung/better-yt-shorts#198]
Whenever I am signed in to my Youtube Account, the scroll bar does not show up in the shorts video. However, when signed in with a different account or not signed in at all, the extension works as normal with the video length scroll bar working. I saw this issue posted previously with it being solved in an update apparently, however, I am currently having this issue. Have for around a month now.

**Comment by watnex** [comment]
I have similar issue. 
When I sign in with my account, youtube shorts buttons are blocking the video. 
When I logout the buttons become normal again.

**Comment by watnex** [comment]
https://support.google.com/youtube/thread/249854085?hl=en&sjid=14959633384519807080-AP

**Comment by watnex** [comment]
Any helps?

**Comment by ynshung** [comment]
This seems to be a very specific issue, could you screenshot how the youtube shorts interface looks like as well as if there's any related error messages in the Console (F12 > Console tab)?

**Comment by watnex** [comment]
> This seems to be a very specific issue, could you screenshot how the youtube shorts interface looks like as well as if there's any related error messages in the Console (F12 > Console tab)?

As the OP have not replied yet, I'm gonna post my screenshots.
Please help.

![yt shorts overlay+account issue](https://github.com/ynshung/better-yt-shorts/assets/99167299/d773430c-eb40-4c31-930d-cdc8aff748c0)

![yt shorts overlay+account issue 2](https://github.com/ynshung/better-yt-shorts/assets/99167299/6570bb43-1913-40c0-9883-56a02d35ac2f)

**Comment by watnex** [comment]
> This seems to be a very specific issue, could you screenshot how the youtube shorts interface looks like as well as if there's any related error messages in the Console (F12 > Console tab)?

Should post more information or should I create a new post for my yt shorts issue?
Please help.

**Comment by ynshung** [comment]
Closing as continued on #218
