### ISSUE TITLE
Autoplay doesnt work on one account, but works on another

### ISSUE THREAD

**Issue by Sekisback** [ynshung/better-yt-shorts#199]
I have a strange behaviour, at first I thought it has something to do with my computer, but it is for sure the Google / Youtube account.

Add-on works fine except the auto scroll function, auto scroll is enabled but the video start from the beginning, no auto scroll.

Then I used the same computer and firefox browser, I only switched the google / youtube account an here the auto scroll works like expected, same behaviour if I dont use a account.
I cleared the cache and all cookies, same behaviour as written above. I switched to chrome and i have the exact behaviour, one account works the other doesn't.

May someone has an idea, or can explain where i have to look for debuging

**Comment by ynshung** [comment]
Could you open the Console (F12 > Console tab) and see if there are any error messages related to bys in it?

**Comment by Sekisback** [comment]
hey, there is no error message,  checked both accounts, can not see a difference between both accounts . Never mind ill delete the broken account after transferring my subscribers lists
