### ISSUE TITLE
Is this code up to date?

### ISSUE THREAD

**Issue by amrut1999** [ynshung/better-yt-shorts#2]
The extension works fine when downloaded from the web store. But doesn't work when I add the extension manually from source. I don't think this code is the same version as the one on the web store.

**Comment by ynshung** [comment]
Hi there, there used to be a bug where the extension won't load when navigating from non-shorts to shorts which doesn't trigger the extension and I think I forget to update them here. I've updated it to include all YouTube url so it should work now.

**Comment by amrut1999** [comment]
So the J and L buttons work when building the extension from source but I don't get the slider and volume control on screen like I do with the chrome webstore extension
