### ISSUE TITLE
The Fullscreen Double Click should have a toggle in the settings so you can disable it.

### ISSUE THREAD

**Issue by Ikeypoo** [ynshung/better-yt-shorts#207]
Accidentally fullscreening does this (already reported) bug where the entire shorts window goes back to the very top or up several shorts. It would be nice to at least be able to disable this feature, until the fullscreen bug is fixed.

**Comment by lephiz69** [comment]
my temp fix until they add a toggle is to just downgrade to 3.2.4 (doesnt have fullscreen)

**Comment by danielaixer** [comment]
> Accidentally fullscreening does this (already reported) bug where the entire shorts window goes back to the very top or up several shorts. It would be nice to at least be able to disable this feature, until the fullscreen bug is fixed.

I was losing my mind wondering why this was happening until I just pinpointed the issue to this addon.

This feature makes it impossible to quickly pause/unpause a short...

**Comment by nnmrt** [comment]
It's not just the full screen that causes you to jump back to the top, it's also when you try to select the text of a comment.
