### ISSUE TITLE
Subscribe button

### ISSUE THREAD

**Issue by huachuman** [ynshung/better-yt-shorts#210]
**Is your feature request related to a problem? Please describe.**
I would subscribe to a lot more channels if there was a subscribe button beside shorts.

**Describe the solution you'd like**
An extra button on the right hand side to subscribe to a short's channel.

**Describe alternatives you've considered**
Manually visiting the channel's page and subscribing

**Additional context**

**Comment by KieranDevvs** [comment]
It already exists without the plugin by default. 
![image](https://github.com/ynshung/better-yt-shorts/assets/21192520/74f3e0d3-25a3-48b4-9bc1-0dfd78fb42cb)

**Comment by huachuman** [comment]
Wow somehow I have never noticed that... I bet more people would subscribe to channels if the button was on the right.

Thanks!
