### ISSUE TITLE
Lost some functions

### ISSUE THREAD

**Issue by Luke0094** [ynshung/better-yt-shorts#217]
**Describe the bug**
Any short doesn't have anymore the clickable slider for timestamp, arrows still work fine (sometimes).
Speed button is missing (the function however still remain if you hold the mouse).
Hide text isn't working.
Not sure who's in the fault here however the title have also slightly more space then it should causing possibly accidental clicks.
Using browser back and forth will cause the extenson to not load correctly and a refresh page is needed.

**Screenshots**
Random short
<img width="540" alt="image" src="https://github.com/ynshung/better-yt-shorts/assets/57552558/01a0e60d-cd0b-4f4c-a68d-aad7a52b1239">

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Brave, Version 1.63.133, Chromium: 121.0.6167.85
- Version of Better YouTube Shorts: 3.5.1

**Comment by adsuth** [comment]
![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/82cdf120-abf3-4c3b-a1da-7f30457e2337)

seems like the HTML has changed again, breaking this.

**Comment by adsuth** [comment]
I've provided a potential fix for this in PR #220

**Comment by Luke0094** [comment]
I guess is fixed now (tho i dislike the new position of the buttons xD)

**Comment by ynshung** [comment]
Issue should be fixed, let us know if the issue still persists in the latest version (v3.6.0)
