### ISSUE TITLE
Youtube shorts overlay buttons on top of videos. Account related. Problem only exists on one account.

### ISSUE THREAD

**Issue by watnex** [ynshung/better-yt-shorts#218]
Youtube shorts buttons are showing in front of videos.
The overlays move to left side for a few centimeters.

![thread-249854085-14643004080982466734](https://github.com/ynshung/better-yt-shorts/assets/99167299/3ce439c7-cc1c-4ff1-91bb-7c2a7e69cc0d)
![thread-249854085-14643004080982467107](https://github.com/ynshung/better-yt-shorts/assets/99167299/527812ab-e651-4ab0-9f9b-093a60c4cfe9)

Things I tried:
1. Clean reinstall chrome. Deleted all chrome related folders.
2. Clear Chrome cache, temp files and history.
3. Disable all extensions.
4. Tried relogin, used different browser, used incognito mode. 

I tried using incognito mode and it works perfectly.
But when I login in incognito mode, the problem appears again.

I tried using firefox.
Without login, it works perfectly.
After Login, the problem appears.

**The problem clearly sticks to my youtube account.**
What can I do to solve the problem?

- OS: Win 10
- Browser: Does not matter. Tried Chrome, Firefox, Ipad Chrome Desktop version
- Version of Better YouTube Shorts: 3.5.1

I posted a question on youtube forum, no anwser.
(https://support.google.com/youtube/thread/249854085?hl=en&sjid=14959633384519807080-AP)

This problem occur more than a month ago.
I saw similar problem on this site.
#198 and #199 
They are **both account-related**
Is this youtube's problem or extension's problem?
Please Help.

**Comment by adsuth** [comment]
Not sure if this is a BYS issue if it still happens without the extension, but will keep this open for now

**Comment by watnex** [comment]
> Not sure if this is a BYS issue if it still happens without the extension, but will keep this open for now

Thanks.
Do I need to post screenshots of error codes?

Do you know where can I contact youtube CS?
I posted it on their forum and there are no replies.

**Comment by ynshung** [comment]
It's probably an issue within YouTube if it also occurs in incognito mode without the extension enabled. Even though it's not related to the extension will be leaving this open and see if there's any other user also came across this issue (if you're facing one please leave a comment below!)

**Comment by Luke0094** [comment]
I might just saying however the problem might be resolution related, a lot of stuff are no longer correctly working with resolution lower the 1920x1080 so sometimes stuff might be overflap on each other, try zooming out if this change something.
Is weird tho that the issue is visible only once you log in (pixel counts?).

**Comment by watnex** [comment]
> I might just saying however the problem might be resolution related, a lot of stuff are no longer correctly working with resolution lower the 1920x1080 so sometimes stuff might be overflap on each other, try zooming out if this change something. Is weird tho that the issue is visible only once you log in (pixel counts?).

I tried ctrl+scroll. The problem still persists.
Yeah, the problem only occurs when I have logged in.
I feel weird too, I have never experienced any problem that stick to an account before.

**Comment by watnex** [comment]
The issue fixed itself. Strange.
Does that mean youtube notice this issue?
Anyway, I will close this issue.
Thanks for the help.
