### ISSUE TITLE
Youtube shorts buttons are showing in front of videos.

### ISSUE THREAD

**Issue by MaviYonca** [ynshung/better-yt-shorts#219]
![Ekran görüntüsü 2024-01-27 134908](https://github.com/ynshung/better-yt-shorts/assets/157886150/10ca0329-ae3b-4904-bea3-32bc903e2fc0)

Things I tried:

   1. I deleted the better-yt-shorts extension and reinstalled it.

I tried using incognito mode and it works fine.

- OS: Windows 11

- Browser:Chrome 120.0.6099.225
- Version of Better YouTube Shorts: v3.5.1

**Comment by ynshung** [comment]
Thanks for the report, internal layout changes within YouTube causes this problem again, should be fixed in #222 on v3.6.0 (Firefox has updated the extension as of 29th Jan 5AM GMT+8)
