### ISSUE TITLE
Every day there is a different bug

### ISSUE THREAD

**Issue by MaviYonca** [ynshung/better-yt-shorts#221]
![Ekran görüntüsü 2024-01-28 131253](https://github.com/ynshung/better-yt-shorts/assets/157886150/698f3a02-ca58-41f6-83a8-25c02a71c3e8)

There was this bug yesterday too
  
     https://github.com/ynshung/better-yt-shorts/issues/219

Things I tried:

      1. I deleted the better-yt-shorts extension and reinstalled it.
      2. I deleted youtube cookies

I tried using incognito mode and it works broken.

- OS: Windows 11
- Browser: Chrome 121.0.6167.86 
- Version of Better YouTube Shorts: v3.5.1

**Comment by ynshung** [comment]
This should be fixed in v2.6.0, please let us know if the issue still persists, thanks!
