### ISSUE TITLE
Seek feature not working

### ISSUE THREAD

**Issue by Brotheus** [ynshung/better-yt-shorts#223]

**Comment by tiagohconte** [comment]
Which OS and browser? It happens on incognito mode?

**Comment by 5e** [comment]
Same here but it fixed itself (lol) after closing tab and just opening a new one.

Windows 10, Firefox

**Comment by 5e** [comment]
It happened again but I still don't know any reproduction steps, pressing left and right arrows does seek correctly, but when hovering over the progress bar it doesn't do anything

![image](https://github.com/ynshung/better-yt-shorts/assets/107583272/196934e9-8912-44c4-b2d2-ac2ea49aa429)

**Comment by Waghabond** [comment]
I think the reproduction step is to scroll back to a previous short. If you scroll down and only go to new shorts it continues working, but if you scroll back to a previous short the whole thing (volume slider + seekbar) breaks and doesn't work until you reload the tab.

can someone else please confirm this?

**Comment by Luke0094** [comment]
100% connected with #230
