### ISSUE TITLE
Volume slider disappear after navigation to the next shorts

### ISSUE THREAD

**Issue by Luke0094** [ynshung/better-yt-shorts#230]
**Describe the bug**
If you return to the first short in the page the volume slider will disappear and will affect also the following shorts, this effect will remain until you don't manually refresh the page.

**To Reproduce**

1. Open a short
2. Go to the second short
3. Get back to the first short

**Desktop (please complete the following information):**

- OS: Windows 11 build 22621.3085
- Browser: Brave [Versione 1.63.138 Chromium: 121.0.6167.85 (Build ufficiale) beta (a 64 bit)]
- Version of Better YouTube Shorts: v3.6.0

**Comment by ynshung** [comment]
This occurs to all shorts i.e. after viewing any shorts, go to the next shorts and go back to it the volume slider no longer appears

**Comment by Waghabond** [comment]
seekbar also breaks

**Comment by Luke0094** [comment]
That is a recent addition after last patch (to be fair before it wasn't working at all).

**Comment by tiagohconte** [comment]
@ynshung @adsuth These recent issues are probably related to the Injection states. The injection is performed only on the first time a short is opened, when returning to the short the injections will not occur!

It looks like the Actions Elements is the only unit that doesn't have to be re-injected.
