### ISSUE TITLE
Progressbar disappearing if you reopen a short

### ISSUE THREAD

**Issue by MrMugame** [ynshung/better-yt-shorts#233]
**Describe the bug**
If you scroll through shorts and then scroll back up to a short you already watched the progressbar disappears / doesn't work anymore.

**To Reproduce**
1. Scroll down at least one short
2. Scroll back up
3. Check progressbar.

**Desktop:**
- OS: Windows 10 or Archlinux
- Browser: Firefox or Chrome.
- Version of Better YouTube Shorts: 3.6.1

(Problem is independent of platform)

**Additional context**
This is due to the fact that yt shorts deletes most of the content from the `ytd-reel-video-renderer` element or specifically from the `#player-container` div, including the progressbar div and everything inside, so also the inserted stuff. If you scroll back up everything gets regenerated but all the stuff the addon added is lost. I think one shouldn't rely on yt keeping or not keeping elements. So every time a renderer with a new id is active the plugin should just add everything in again (like yt does themselves). This would also make all the `Set` stuff obsolete.

**Comment by Luke0094** [comment]
Problem already mentioned in #230

**Comment by MrMugame** [comment]
Closing as it's a duplicate and the progressbar is now a youtube native feature
