### ISSUE TITLE
Timeline slider breaks after scrolling to the next short

### ISSUE THREAD

**Issue by CodeLabsCEO** [ynshung/better-yt-shorts#236]
**Describe the bug**

Timeline slider breaks after scrolling to the next short

**To Reproduce**

1. Go to 'yt.com.'
2. Click on 'shorts'
3. Scroll down to 'watch a short keep scrolling down and eventually the timeline slider will break.'

**Expected behavior**
Timeline slider to still be accessible.

**Screenshots**
![image](https://github.com/ynshung/better-yt-shorts/assets/123798868/41d74d69-4a3f-42b0-9815-cd683d46710c)

**Desktop**

- OS: [Win 11 Pro]
- Browser: [Chrome Version 122.0.6261.96]
- Version of Better YouTube Shorts: [Tried 3.6.0, 3.7.0]

**Comment by tiagohconte** [comment]
Related to #230.

I explained the cause in [my comment](https://github.com/ynshung/better-yt-shorts/issues/230#issuecomment-1937401178).
