### ISSUE TITLE
Volume bar on YTmusic is moved to the right.

### ISSUE THREAD

**Issue by DED0TATED** [ynshung/better-yt-shorts#25]
The volume slider on youtube music is being moved to the far right of the screen for some reason. Turning off the extension fixes this issue and moves the volume slider back to its correct spot. I'm using the Firefox version btw.

**Comment by ynshung** [comment]
Should be fixed from aa668beb58ac83d517aa8bcba288fbf7bff971f6, can you test it out?

**Comment by DED0TATED** [comment]
It's still in a different location, but I'd say it's functionally fixed as I was barely able to use the slider before but now I can. Here's what I mean: https://imgur.com/a/TyiobSt
