### ISSUE TITLE
Exception raised while trying to skip ahead/back: Can't convert null to object 2 [Firefox]

### ISSUE THREAD

**Issue by deridiot** [ynshung/better-yt-shorts#26]
Browser: Firefox 110.0
OS: Linux Mint 21.1
Extension Version: 2.1.1

Basically "nothing works" (tm). None of the set shortcuts does anything aside of raising the following error in console:
```
TypeError: can't convert null to object 2 [content-script.js:26:39](moz-extension://5c1cbd0a-0138-48dd-b358-dbbdc7a878e2/content-script.js)
    <anonym> moz-extension://5c1cbd0a-0138-48dd-b358-dbbdc7a878e2/content-script.js:26
```
which is:
```
for (const [cmd, keybind] of Object.entries(keybinds)) if (key === keybind) command = cmd;
```

So yeah the yt-keybinds object the code depends on is not existing.

Trying to change the keybindings does absolutely nothing. Not even an error is raised in console.

Solution:
Manually create the yt-keybinds key in localstorage with the values:
```
{"Decrease Speed":"u","Decrease Volume":"-","Increase Speed":"o","Increase Volume":"+","Reset Speed":"i","Seek Backward":"j","Seek Forward":"l","Toggle Mute":"m"}
```
That does not fix changing the keybindings, but makes the extension usable at least.

**Comment by ynshung** [comment]
Version submitted and should be updated in a few minutes. Thanks for the report!
