### ISSUE TITLE
shows warning: 'browser_action' requires manifest version of 2 or lower.

### ISSUE THREAD

**Issue by rudrakpatra** [ynshung/better-yt-shorts#28]
in the manifest.json
```
   "browser_action": {
        "default_popup": "popup.html"
    },

```
requires manifest version of 2 or lower

**Comment by ynshung** [comment]
For chrome browser, this part should be removed as it's already covered by `action`'s `default_popup`. It's put there for combability with other browser that uses manifest v2 such as firefox.
