### ISSUE TITLE
Chrome extension: mentions v2.3.0 but no changes to popup

### ISSUE THREAD

**Issue by E-RELevant** [ynshung/better-yt-shorts#41]
[Commit](https://github.com/ynshung/better-yt-shorts/commit/407b847d9e9457d58c9b8eb7d3b4a0d8a7a08bae)
![image](https://user-images.githubusercontent.com/20738487/232817693-c8bc6159-f4f1-4b2c-b476-3e6503d4c3b6.png)

**Comment by ynshung** [comment]
Thanks for the report, seems like I misuploaded the file there😅
