### ISSUE TITLE
Scrolling on speed of video doesn't change the speed

### ISSUE THREAD

**Issue by JoshuaMUlman** [ynshung/better-yt-shorts#42]
Perhaps I am trying the wrong thing but the description says "Scroll on the speed and time indicator to change its speed and seek." I am trying to control the speed of the short without using the hotkey buttons and it does not appear to work.

Hovering over the speed button and scrolling gives the same behavior as normal for shorts, moving up and down the videos.

I'm using v2.3.0 on Firefox.

**Comment by takoyaki88e** [comment]
An unsupported event listener was used. Fixed in #43, please wait until it is applied...🙇‍♂️

**Comment by ynshung** [comment]
New version is submitted, will be updated within a day!
