### ISSUE TITLE
feature request: enable to pause using space bar.

### ISSUE THREAD

**Issue by pgr-a** [ynshung/better-yt-shorts#44]
im used to press space for pause from any other player. shorts skip the video on space. very annoying. please add an option do change that behavior.

**Comment by ynshung** [comment]
Thank you for the notification of the bug! (which originate from YouTube themselves) It is now fixed in 327cc7f and will be updated in the extension webstore in a few hours.

**Comment by pgr-a** [comment]
thanks, fantastic!
