### ISSUE TITLE
Time skipping in progress bar is inaccurate when opening comments

### ISSUE THREAD

**Issue by takoyaki88e** [ynshung/better-yt-shorts#48]
The more you try to skip to a later time, the larger the error.

https://github.com/ynshung/better-yt-shorts/assets/78483821/ff689ae1-7b07-439e-8286-6e18fb41e370

Also, when this bug occurs, the timestamp tooltip that appears when hovering does not seem to appear

**Comment by monsieurvor** [comment]
Should be fixed in PR #51
