### ISSUE TITLE
Volume control not working at Firefox

### ISSUE THREAD

**Issue by Chris6ix** [ynshung/better-yt-shorts#50]
The addon works pretty well, except for the volume controls. They just don't work at all.

The volume slider that is shown in the image is just not there, and pressing "+" or "-" does nothing.

If it helps, I'm using Better YT Shorts 2.4.0 in Firefox 114.0.2 (64-bit) on Windows 11 22621.1848
They seem all be the latest versions as of now.

**Comment by Chris6ix** [comment]
I'm not sure why, but now on the 2nd day of using Better YT Shorts, the Volume control suddenly works.
Leaving this open for now if the issue comes back.

**Comment by Volodesi** [comment]
It sort of works for me on Brave Browser.

Only issue is the sound jumps up to max volume for a second after the video starts, then goes back to where I set it.

**Comment by Chris6ix** [comment]
Yeah, I also have that issue with the volume control only adjusting the sound like half a second after the short has started, but that only a minor issue imo.

Since I have been using it for a week now, I can confirm that my original issue with the Volume control not working at all is still a thing, but only sometimes.
Sometimes the volume control works perfectly, sometimes it doesn't at all. Refreshing the page has fixed it once for me, but the other times it has not. 
I really don't know what causes it or even how to replicate it, but "It sort of works" is literally the best description for the feature :/

@ynshung do you maybe have a debug mode or something so that we could find out what causes this?

**Comment by ynshung** [comment]
We don't really have a debug mode except tinkering with the source code itself and check where is wrong within it. I will try to work on it once I'm free, but it would be great if anyone could help on it

**Comment by ynshung** [comment]
Does the issue still persists? If no, I will be closing this issue soon
