### ISSUE TITLE
Option to disable and enable options/features

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#52]
An option to manually disable and enable each of the options offered by the extension would be nice. _(Submitted anonymously on Google Form)_

**Comment by adsuth** [comment]
Could I get a list of the features they'd like to disable?
I assume this would mean content script actions like speed up/down, autoplay, etc
Could add this in v3, adding a new page on the popup to enable/ disable certain injected elements

**Comment by ynshung** [comment]
The user doesn't really provide the list, but yeah I would believe tis the content script actions. This could be put on low priority
