### ISSUE TITLE
Seekbar does not show up for video less than 30s

### ISSUE THREAD

**Issue by kdizzy07** [ynshung/better-yt-shorts#53]
Sometimes refresh fixes it. sometimes not.
Hope you can reproduce. On this vid refresh didn't fix it:
https://www.youtube.com/shorts/K4T_PBvEw8s

**Comment by ynshung** [comment]
Just a quick note: It seems to be a problem that happened to video lesser than 30s. This [code segment](https://github.com/ynshung/better-yt-shorts/blob/be6f7279601ce07e715bd96fb8f972eb18687739/content-script.js#L353) seems to aim to fix this problem but it doesn't work for the most part.
