### ISSUE TITLE
v3: Rebuilding to use Vite/Webpack, React, Typescript etc.

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#62]
Perhaps we can switch over to use tools such as [CRXJS](https://crxjs.dev/vite-plugin/), convert to Typescript and use framework like React? It may help improve the efficiency of the development. It would take some time to rebuild from scratch though.

**Comment by adsuth** [comment]
Currently working on porting the project to react atm (well, the content script stuff is just typescript and the popup is react. Wasnt sure how using react would even work with the content script side given that the root is constantly changing).

You can see my progress [here](https://github.com/adsuth/better-yt-shorts/tree/crxjs-port)

It's nowhere near done mind you, but the popup is visually working (the options work, still not done keybinds yet).
This is the first real thing I've tried making in React and TS so I'm definitely breaking some core conventions. Hopefully they can be cleared up down the road (i'm having one particularly annoying issue where the input box keeps unfocusing whenever you type anything)

As for the content script, I just copy/pasted it over and moved some things around. Nowhere near done either. May need some help figuring out how those extra frontend buttons + the timeline are created

As a heads up, **I'm only testing on chrome**. However, all we really use is storage, and its being imported the same way (it'll check for chrome/browser like before)

I can say though that working with this is SO much better than having to constantly refresh the extension and tab haha

![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/bda1db46-1196-4b75-8742-4950daae2559)

**Comment by ynshung** [comment]
Looks very nice! Thank you so much for the initiative and hopefully it'll improve the development process for the future.

It'll be great if you can sync your progress with the v3 branch in this repository, thanks!

**Comment by ynshung** [comment]
Some extensions we can refer to (will be updated):
https://github.com/probablyraging/hide-youtube-shorts

**Comment by ynshung** [comment]
Hi @adsuth, I had clone your fork's branch into the v3 branch here (https://github.com/ynshung/better-yt-shorts/tree/v3). It would be great if you could work on it right on this repository, thanks!

**Comment by adsuth** [comment]
Hi @ynshung, just want to announce that v3 is done (well, at the very least, I think its in a good state at the moment on chromium based browsers. I've tested it on Edge, Chromium, Chrome and Brave).

However, I have no idea how to get it working on Firefox. Looking into it, it seems that CRXJS doesnt support FF at the moment which sucks, could maybe try to find a way to manually port it?

**Comment by ynshung** [comment]
Thanks @adsuth so much for the contribution! I think all that's left is working on building on Firefox and the logo design. I might tinker around with the code as well.

**Comment by ynshung** [comment]
The autoplay button seems to broke suddenly, can you help take a look? @adsuth 

![image](https://github.com/ynshung/better-yt-shorts/assets/61302840/1c43c754-7401-4293-8749-1d58de135c21)

**Comment by adsuth** [comment]
> The autoplay button seems to broke suddenly, can you help take a look? @adsuth
> 
> ![image](https://user-images.githubusercontent.com/61302840/261673226-1c43c754-7401-4293-8749-1d58de135c21.png)

Hi, got this fixed (I think I just messed up my conversion)

<img width="91" alt="image" src="https://github.com/ynshung/better-yt-shorts/assets/74009107/c23cd36d-c4f4-49d7-82f2-8a88b70d417c">

**Comment by ynshung** [comment]
Closing this issue, moving discussion to the PR itself
