### ISSUE TITLE
Disable controls when writing comments

### ISSUE THREAD

**Issue by NicolasGoeddel** [ynshung/better-yt-shorts#7]
Everytime I write a new comment to a short it randomly skips through the video in the background or changes its speed. Please disable the hotkeys while the comment dialog is open.

**Comment by Beach77** [comment]
Just came to see if someone else had this issue because it's getting very annoying tbh. Giving us the ability to assign hotkeys would also fix this.

**Comment by ynshung** [comment]
Fixed from #16 and the new version is already submitted for review, expecting to be published in a day or two. Special thanks to @monsieurvor!
