### ISSUE TITLE
[Urgent] Logo Redesign

### ISSUE THREAD

**Issue by ynshung** [ynshung/better-yt-shorts#70]
I have received an email regarding the extension that it violates the YouTube Shorts Logo trademark (oops). As such we need to update the logo asap to avoid suspension from Google.

As such, if anyone is interested in taking up the task of redesigning the logo please let me know, thank you!

**Comment by adsuth** [comment]
I may be able to make one up, any ideas for what you'd like it be?

Theres the mock one i made to differentiate my react remake from the og which was this, but that may be too similar as well

![bys-128](https://github.com/ynshung/better-yt-shorts/assets/74009107/2a4a59c0-06bb-42e0-b704-70005436ff32)

**Comment by t4sh** [comment]
I like your extension and was surprised to see it discontinued/unpublished from the Chrome Web Store.
What is the cited violation for? the YT Shorts logo usage?

In that case, please see if this helps get around 
![byts16](https://github.com/ynshung/better-yt-shorts/assets/1670383/42bcee54-33f5-496a-8da7-a5670f93cb49)
![byts32](https://github.com/ynshung/better-yt-shorts/assets/1670383/abdeceab-677d-4d89-a324-800e1570bee4)
![byts48](https://github.com/ynshung/better-yt-shorts/assets/1670383/4ccead89-0b82-4408-82d5-0f0c6ddea319)
![byts128](https://github.com/ynshung/better-yt-shorts/assets/1670383/b760e8e1-11bf-47f9-8f7d-6b418622ddd6)

(very quick update)
- highlight "S" with the lightening bolt, and 
- "B" from the part of shorts logo to retain hint of outline, but make it different shape
- different colors than default logo

**Comment by t4sh** [comment]
I like your extension and was surprised to see it discontinued/unpublished from the Chrome Web Store.
What is the cited violation for? the YT Shorts logo usage?

In that case, please see if this helps get around 
![byts16](https://github.com/ynshung/better-yt-shorts/assets/1670383/65bd742d-fcf3-4e0e-a8fb-f65528165967)
![byts32](https://github.com/ynshung/better-yt-shorts/assets/1670383/f25c8f7c-9557-4250-aff0-8c5e256a6e60)
![byts48](https://github.com/ynshung/better-yt-shorts/assets/1670383/cf071560-36bd-4f94-b65e-df4df8321895)
![byts128](https://github.com/ynshung/better-yt-shorts/assets/1670383/0561a041-dde8-4e57-9c6f-9c4a19134be2)


Generally it takes care of uniqueness based on
- highlight "S" with the lightening bolt, and 
- "B" from the part of shorts logo to retain hint of outline, but make it different shape
- different colors than default logo
- works in light and dark themes

Was a very quick update! Can make variations and updates based on comments, or can even help explore if you've any other idea.

**Comment by adsuth** [comment]
Another potential option. This design aims to simplify the existing logo while removing any potentially coprighted material (the general shorts shape and (potentially) the youtube color which may or may not be copyrighted). Basically, just take the red of the backing, and apply it to a custom thumbs up

![bys-16](https://github.com/ynshung/better-yt-shorts/assets/74009107/9beac603-88a6-45ef-a51c-29c25e853374)
![bys-32](https://github.com/ynshung/better-yt-shorts/assets/74009107/4d2bedf4-bfb9-4421-ae5a-6a2c5a16e24e)
![bys-48](https://github.com/ynshung/better-yt-shorts/assets/74009107/5da657bf-e65e-43cb-9a14-6e6be128083b)
![bys-128](https://github.com/ynshung/better-yt-shorts/assets/74009107/1d83e1db-226b-4f66-8b2e-2f9d27410070)

Partly inspired by the grainy, urban look of twitter (just thought it made the relatively simple look a bit more interesting)
I tried creating this design with the golden circles... the actual success of that is debatable haha 

![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/e24c8179-b3e3-4407-b59c-bf7965f85607)

**There are also a few variations, and if you'd prefer one of those or any other potential changes, let me know and I'll get to it.**

![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/7661ce7f-a917-4e10-9c7c-3f6012b331b1)
![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/7ff04da0-8bbc-4f0e-8560-c8300849fde8)
![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/96e8e843-2940-4d04-b7c0-1ff44ec2f770)
![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/1cdf278e-b28e-4e6d-94ff-889b81bdb9e3)

**Comment by ynshung** [comment]
Thank you guys for the help! I will be designing another logo which I have in mind and would probably finish it within a week or two.

**Comment by ynshung** [comment]
Here is the logo I've designed with inspiration from some AI tools:

![bys-v2-logo](https://github.com/ynshung/better-yt-shorts/assets/61302840/3f71f99e-316a-4b98-9199-7e63b36cd338)

It represent the "B" alphabet which is stands for the first alphabet of the extension's name. There's also a play button in the centre symbolizing YouTube play button. Feel free to let me know your thoughts

**Comment by t4sh** [comment]
This looks good!!

and thanks! the extension is back on the store.

Minor quip, if there is one is the direction of the play button.. Can it be facing left? anyways, given the extension is mostly in background. does not matter much, what matters is the extension is on store, and is identifiable!
