### ISSUE TITLE
Suggestion: Add FULLSCREEN button / keybind (F?)

### ISSUE THREAD

**Issue by ronaldweeph** [ynshung/better-yt-shorts#74]
Hi! First off, love your extension and I find it **SO USEFUL! THANK YOU** for making it and keeping it free. 

Would it be doable to add an option for **FULLSCREEN** Shorts viewing in the form of a button and a keyboard shortcut (perhaps the already establised 'F' key) ?? I think the extension is already great as it is but in my personal use case, wish there was a way to fullscreen. Thank you!

**Comment by ynshung** [comment]
I was thinking about the simple F11 full screen which would suffice, but I believe you wanted to also be able to remap the F11 to other keys?

There's an existing [extension](https://chrome.google.com/webstore/detail/shortsfullscreen/molcegabghkphlnemjfciclgoooejakj) that I found as well, which remove the top search bar and the sidebar, though the shorts doesn't expand vertically.

**Comment by ronaldweeph** [comment]
Thanks for the reply. I guess you're on Windows/PC?? I'm using a Mac by the way so no such F11 function (it's a volume down button in my model). Also tried Fn+F11 with a YouTube page open but nothing happens.

Yes, I'm already using 'ShortsFullscreen' extension and it works well but it would be great if you could also add such feature in Better YouTube Shorts since you were able to implement much more complex/intricate features in that extension so in my mind, adding such a simple fullscreen option would be piece of cake for you?? In that way, I just need your extension and can remove the rest?? 😁

Hope you could consider. Thank you.

**Comment by ronaldweeph** [comment]
Unresponsive. I guess not, eh?? Sorry to have bothered you. Nevermind
