### ISSUE TITLE
Guide to install as a unpacked extension

### ISSUE THREAD

**Issue by GabbeHags** [ynshung/better-yt-shorts#81]
Now when this extension have been removed from Chrome, I would like to know how to install this as an unpacked extension.

**Comment by Notnilc2107** [comment]
1. go to the github page https://github.com/ynshung/better-yt-shorts
2. click the green button that says "<> code"
3. click "download zip"
4. extract zip file
5. go to the "manage extensions" page chrome://extensions/
6. click load unpacked
7. navigate to the folder that has the extracted files in the file browser that pops up. you might need to navigate another layer deep; the folder you navigate to should contain a file named "manifest.json"
8. click select folder

**Comment by ynshung** [comment]
Hi all, just a notice that the extension is republished with a new link: https://chrome.google.com/webstore/detail/better-youtube-shorts/pehohlhkhbcfdneocgnfbnilppmfncdg
I have also included the guide in the README file as well. Thank you guys for the support
