### ISSUE TITLE
Shift+default Keybinds still works even though changed Keybinds

### ISSUE THREAD

**Issue by HealingArcYT** [ynshung/better-yt-shorts#89]
Im pretty sure (gonna check after writing this) that i already created an issue with typing in the comments still being interpreted as input. as WKey and SKey are used for scrolling through shorts by default, i set those to be something different so that when i type in the comments it doesnt just go to the next short and discards my comment. BUT: when i use shift+w or shift+s for some reason it still skips to the next/previous short.

**Comment by HealingArcYT** [comment]
Ok i havent created that other issue i mentioned in the opening message, but it still exists

**Comment by adsuth** [comment]
I cant replicate Shift+Default. Did you refresh the page after changing the bindings? v2 needs a page refresh to register changed binds.

modifier key + bind however is definitely an issue that needs addressed (also binds should be ignored if focused on an element. I think theres already something in place for that, and I cant replicate this either, but may need further testing)

**Comment by HealingArcYT** [comment]
ok the shift+default bind i cant get right now, but if you reply to a comment on a short and hit buttons that do stuff, this stuff gets done

**Comment by adsuth** [comment]
So you mean like typing a comment, clicking off (eg clicking the like button), and then pressing a bind? Because in that case youre no longer focused on the text input, and thats the intended behavior

**Comment by HealingArcYT** [comment]
no, while typing into the reply to a comment, it changes the playback speed, skips frames if i use "." or "," or if i use my arrows to correct something it fast forwards or rewinds accordingly.

**Comment by adsuth** [comment]
Found the issue and I've addressed it in this PR
