### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by Beach77** [ynshung/better-yt-shorts#9]
It was working fine last time I used it which I think was yesterday. Only thing that still works is pressing K(pause). On some shorts it works if I refresh the page but when I switch short it stops working again. 

EDIT: I found a fix of a sort, if you press anywhere next to the video then it starts working again but you have to do it on every short.

**Comment by Beach77** [comment]
Ok very weird al of a sudden it's working again. Don't know what the problem was. Don't know how to delete issue, sorry.

**Comment by dekotale** [comment]
I just send a pull request that fix this issue. waiting to be approved. #10

**Comment by Beach77** [comment]
> I just send a pull request that fix this issue. waiting to be approved. #10

Thank you very much! Hopefully you get approved.

**Comment by ynshung** [comment]
> > I just send a pull request that fix this issue. waiting to be approved. #10
> 
> Thank you very much! Hopefully you get approved. Is there any way to add this manually without having to wait for approval on Firefox?

New version is uploading soon! Will be released once the version is approved.
