### ISSUE TITLE
Can we see the number of views in shorts? 

### ISSUE THREAD

**Issue by GitAcc53** [ynshung/better-yt-shorts#91]
In normal videos we can see the views but not in shorts. In shorts, we have to click 3 dots and Description to see the views.

**Comment by adsuth** [comment]
![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/6d51e451-233e-4a0d-a1e9-ad6beb210db7)

I may be missing something, but I can't see a view count regardless?
It is recorded though, and can be seen in the full youtube view
![image](https://github.com/ynshung/better-yt-shorts/assets/74009107/1ba8d948-9bac-4fdd-a440-438f6ade98a9)

That being said, I dont think there's any easy way to access the view count on the shorts view

**Comment by GitAcc53** [comment]
> ![image](https://user-images.githubusercontent.com/74009107/266340559-6d51e451-233e-4a0d-a1e9-ad6beb210db7.png)
> 
> I may be missing something, but I can't see a view count regardless? It is recorded though, and can be seen in the full youtube view ![image](https://user-images.githubusercontent.com/74009107/266342160-1ba8d948-9bac-4fdd-a440-438f6ade98a9.png)
> 
> That being said, I dont think there's any easy way to access the view count on the shorts view

"I may be missing something, but I can't see a view count regardless?"

Thats what I am saying. We can't see the views on Shorts. It can be seen in non-short version, it says "324K views", but it can't be seen on shorts.

**Comment by adsuth** [comment]
> In shorts, we have to click 3 dots and Description to see the views.

Right. This in particular threw me off.

I dont think this would be possible as the information isnt accessible on the page
Though if somebody can prove me wrong, by all means. Itd be a neat addition

**Comment by SamiSul** [comment]
@adsuth [i created a PR for this](https://github.com/ynshung/better-yt-shorts/pull/140). Can something like this work?
