### ISSUE TITLE
Every shorts skipped on other languages

### ISSUE THREAD

**Issue by Maouniel** [ynshung/better-yt-shorts#92]
When i enable “Skip shorts with fewer likes”, script skips EVERY video no matter how many likes it has. 
That's a language issue, cause when i switch (from russian) to english - extension works fine.

**Comment by adsuth** [comment]
Issue is with the regex that checks for the multiplier part of the like count at ./content-script.js:685
No idea how the regex works mind you, @swolewizard wrote it if iirc

` /^(\d{1,3}(?:(?:,\d{3})*(?:\.\d+)?)|(?:\d+))(?:([,.])(\d+))?([a-z]*)\.?$/i;`

I assume its not including Cyrillic characters? No idea how to fix it unfortunately, regex scares me.
