### ISSUE TITLE
Update V3 With New V2 Patches

### ISSUE THREAD

**Issue by adsuth** [ynshung/better-yt-shorts#98]
Most if not all changes on V2 - mostly fixes for issues - will have to be replicated for V3 as I've not been keeping it up to date.

Not sure where I'd get a list, though I assume it'd just be a case of sorting the V2 PRs by date and going through all the ones made after August 11th (I think) and adjusting the code to work for V3

**Comment by ynshung** [comment]
Here are some that I compiled, feel free to add or edit the list:

- [ ] #88
- [ ] #89
- [ ] #95
